build:
  nodes:
    analysis:
      environment:
        php:
          version: 7.4

build_failure_conditions:
  - 'elements.rating(<= C).new.exists'                        # No new classes/methods with a rating of C or worse allowed
  - 'project.metric_change("scrutinizer.test_coverage", < 0)' # Code Coverage decreased from previous inspection